export const userDatabaseInject = [
  {
    uniqueID: "1",
    firstName: "Test User",
    lastName: "Industries",
    email: "a",
    password: "a",
  },
  {
    uniqueID: "2",
    firstName: "Alyssa Merkadio",
    lastName: "De Laysia",
    email: "Alyssa21@gmail.com",
    password: "WhitePeopleHappy",
  },
  {
    uniqueID: "3",
    firstName: "Jenkins Marcolo",
    lastName: "Lenielamo",
    email: "JMLeniel@dlsu.dasma.com.ph",
    password: "Jokrill",
  },
  {
    uniqueID: "4",
    firstName: "Malakai Merquin",
    lastName: "Bobbyacu",
    email: "Malakai@yahoo.com",
    password: "boyoingOW",
  },
  {
    uniqueID: "5",
    firstName: "Pantene Denise",
    lastName: "Danjikwa",
    email: "OPFracture@yahoo.com",
    password: "SolarMower",
  },
  {
    uniqueID: "6",
    firstName: "Quene Victoria",
    lastName: "Taenoda",
    email: "Qazujm@daporta.com.eu",
    password:
      "KP0c@vGu7ysp4EgoFHOUdqv*Tb#m2^K8NW^T!cc8KO!XSOn&K#yUz25DJmYzFTGCq9lrTjy#",
  },
];

export const projectDatabaseInject = [
  {
    uniqueID: "1",
    favoured: true,
    members: [{ uniqueID: "6" }],
    projectName: "Grocery Store - Application",
    backgroundID: "1",
    description: "Application for simulating grocery stores.",
    kanbanID: "",
  },
  {
    uniqueID: "1",
    favoured: false,
    members: [{ uniqueID: "6" }],
    projectName: "Redux Project",
    backgroundID: "1",
    description: "Project Stack of Redux",
    kanbanID: "",
  },
  {
    uniqueID: "1",
    favoured: true,
    members: [{ uniqueID: "6" }],
    projectName: "Hot tub Stream OTW",
    backgroundID: "1",
    description:
      "Get your friends in a all-in-one hang-out in a Hot tub party!",
    kanbanID: "",
  },
  {
    uniqueID: "1",
    favoured: false,
    members: [],
    projectName: "Memorial Queza",
    backgroundID: "2",
    description:
      "This is a test project purposely made for fake data injection.",
    kanbanID: "",
  },
];

export const taskDatabseInject = [
  {
    uniqueID: "1",
    taskID: "1",
    taskName: "Jump 3 miles instaneously.",
    taskDescription: "The federation requires you to do it.",
    kanbanID: "",
    priority: "high",
  },
  {
    uniqueID: "1",
    taskID: "2",
    taskName: "Go insane on a bike.",
    taskDescription: "Swing it!",
    kanbanID: "",
    priority: "high",
  },
  {
    uniqueID: "1",
    taskID: "3",
    taskName: "Do your projects.",
    taskDescription: "Do your boring projects duud.",
    kanbanID: "",
    priority: "low",
  },
  {
    uniqueID: "1",
    taskID: "4",
    taskName:
      "Ask why your program isn't doing what you want it to do, despite you telling it what to do.",
    taskDescription: "Life of a programmer, ey?",
    kanbanID: "",
    priority: "medium",
  },
  {
    uniqueID: "1",
    taskID: "5",
    taskName: "LSS - dance your favorite song",
    taskDescription: "Nothing beats chilling and beating.",
    kanbanID: "",
    priority: "high",
  },
  {
    uniqueID: "2",
    taskID: "1",
    taskName: "Jump 3 miles instaneously.",
    taskDescription: "The federation requires you to do it.",
    kanbanID: "",
    priority: "high",
  },
  {
    uniqueID: "2",
    taskID: "2",
    taskName: "Go insane on a bike.",
    taskDescription: "Swing it!",
    kanbanID: "",
    priority: "high",
  },
  {
    uniqueID: "2",
    taskID: "3",
    taskName: "Do your projects.",
    taskDescription: "Do your boring projects duud.",
    kanbanID: "",
    priority: "low",
  },
  {
    uniqueID: "2",
    taskID: "4",
    taskName:
      "Ask why your program isn't doing what you want it to do, despite you telling it what to do.",
    taskDescription: "Life of a programmer, ey?",
    kanbanID: "",
    priority: "medium",
  },
  {
    uniqueID: "2",
    taskID: "5",
    taskName: "LSS - dance your favorite song",
    taskDescription: "Nothing beats chilling and beating.",
    kanbanID: "",
    priority: "high",
  },
  {
    uniqueID: "3",
    taskID: "1",
    taskName: "Jump 3 miles instaneously.",
    taskDescription: "The federation requires you to do it.",
    kanbanID: "",
    priority: "high",
  },
  {
    uniqueID: "3",
    taskID: "2",
    taskName: "Go insane on a bike.",
    taskDescription: "Swing it!",
    kanbanID: "",
    priority: "high",
  },
  {
    uniqueID: "3",
    taskID: "3",
    taskName: "Do your projects.",
    taskDescription: "Do your boring projects duud.",
    kanbanID: "",
    priority: "low",
  },
  {
    uniqueID: "3",
    taskID: "4",
    taskName:
      "Ask why your program isn't doing what you want it to do, despite you telling it what to do.",
    taskDescription: "Life of a programmer, ey?",
    kanbanID: "",
    priority: "medium",
  },
  {
    uniqueID: "3",
    taskID: "5",
    taskName: "LSS - dance your favorite song",
    taskDescription: "Nothing beats chilling and beating.",
    kanbanID: "",
    priority: "high",
  },
  {
    uniqueID: "4",
    taskID: "1",
    taskName: "Jump 3 miles instaneously.",
    taskDescription: "The federation requires you to do it.",
    kanbanID: "",
    priority: "high",
  },
  {
    uniqueID: "4",
    taskID: "2",
    taskName: "Go insane on a bike.",
    taskDescription: "Swing it!",
    kanbanID: "",
    priority: "high",
  },
  {
    uniqueID: "4",
    taskID: "3",
    taskName: "Do your projects.",
    taskDescription: "Do your boring projects duud.",
    kanbanID: "",
    priority: "low",
  },
  {
    uniqueID: "4",
    taskID: "4",
    taskName:
      "Ask why your program isn't doing what you want it to do, despite you telling it what to do.",
    taskDescription: "Life of a programmer, ey?",
    kanbanID: "",
    priority: "medium",
  },
  {
    uniqueID: "4",
    taskID: "5",
    taskName: "LSS - dance your favorite song",
    taskDescription: "Nothing beats chilling and beating.",
    kanbanID: "",
    priority: "high",
  },
  {
    uniqueID: "5",
    taskID: "1",
    taskName: "Jump 3 miles instaneously.",
    taskDescription: "The federation requires you to do it.",
    kanbanID: "",
    priority: "high",
  },
  {
    uniqueID: "5",
    taskID: "2",
    taskName: "Go insane on a bike.",
    taskDescription: "Swing it!",
    kanbanID: "",
    priority: "high",
  },
  {
    uniqueID: "5",
    taskID: "3",
    taskName: "Do your projects.",
    taskDescription: "Do your boring projects duud.",
    kanbanID: "",
    priority: "low",
  },
  {
    uniqueID: "5",
    taskID: "4",
    taskName:
      "Ask why your program isn't doing what you want it to do, despite you telling it what to do.",
    taskDescription: "Life of a programmer, ey?",
    kanbanID: "",
    priority: "medium",
  },
  {
    uniqueID: "5",
    taskID: "5",
    taskName: "LSS - dance your favorite song",
    taskDescription: "Nothing beats chilling and beating.",
    kanbanID: "",
    priority: "high",
  },
  {
    uniqueID: "6",
    taskID: "1",
    taskName: "Jump 3 miles instaneously.",
    taskDescription: "The federation requires you to do it.",
    kanbanID: "",
    priority: "high",
  },
  {
    uniqueID: "6",
    taskID: "2",
    taskName: "Go insane on a bike.",
    taskDescription: "Swing it!",
    kanbanID: "",
    priority: "high",
  },
  {
    uniqueID: "6",
    taskID: "3",
    taskName: "Do your projects.",
    taskDescription: "Do your boring projects duud.",
    kanbanID: "",
    priority: "low",
  },
  {
    uniqueID: "6",
    taskID: "4",
    taskName:
      "Ask why your program isn't doing what you want it to do, despite you telling it what to do.",
    taskDescription: "Life of a programmer, ey?",
    kanbanID: "",
    priority: "medium",
  },
  {
    uniqueID: "6",
    taskID: "5",
    taskName: "LSS - dance your favorite song",
    taskDescription: "Nothing beats chilling and beating.",
    kanbanID: "",
    priority: "high",
  },
];
